#!/bin/sh
# postinst script for thunderbird hack
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
	if [ -f /tmp/gnomecc.desktop ]; then
		cp /tmp/thunderbird.desktop /usr/share/applications/thunderbird.desktop
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "argumentos \`$1'" >&2
        exit 1
    ;;
esac

exit 0
